version: "2"
volumes:
  node_modules:
services:
  frontend_dev_server:
    # Uncomment to use member webpack: command: ./node_modules/.bin/webpack-dev-server --config member.webpack.config.js
    image: makeradmin/frontend_dev_server:1.0
    build:
      context: .
      dockerfile: ./DevServerDockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/frontend
      - node_modules:/frontend/node_modules
