version: "2"
services:
  db2:
    image: mysql:5.7
    # The lumen library seems to use an older mysql client which is not able to connect if mysql uses the newer caching_sha2_password authentication plugin.
    # Therefore we need to override the mysql starting command to set a config option to use the older password authentication plugin.
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./logs/mysql:/var/www/html/storage/logs
    environment:
      # Note: the config only seems to be updated when the container is initially created.
      # If the db config needs to be changed then the db image and volume needs to be destroyed first.
      MYSQL_DATABASE: "${MYSQL_DB}"
      MYSQL_ROOT_HOST: "db2"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASS}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - makeradmin

  servicebase:
    image: makeradmin/servicebase:1.0
    build:
      context: ./library
      dockerfile: DockerfileServiceBase
    networks:
      - makeradmin

  library:
    image: makeradmin/library:1.0
    build:
      context: ./library
      dockerfile: Dockerfile
    depends_on:
      - servicebase
    networks:
      - makeradmin

  servicebase_python:
    image: makeradmin/servicebase_python:1.0
    build:
      context: ./servicebase_python
    networks:
      - makeradmin

  api-gateway:
    image: makeradmin/apigateway:1.0
    build:
      context: ./apigateway
      dockerfile: ${PWD}/library/DockerfileService
    volumes:
      - ./logs/apigateway:/var/www/html/storage/logs
      - ./apigateway/lumen/routes:/var/www/html/routes
      - ./apigateway/lumen/app:/var/www/html/app
      - ./library/src/Makeradmin:/var/www/html/library
    depends_on:
      - db2
      - servicebase
      - library
    ports:
      - "8010:80"
    networks:
      - makeradmin
    environment:
      APP_DEBUG: "true"
      MYSQL_HOST: "db2:${MYSQL_PORT}"
      MYSQL_DB: "makeradmin-apigateway"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASS: "${MYSQL_PASS}"
      BEARER: "${API_BEARER}"

  current-member:
    image: makeradmin/current-member:1.0
    build: member_view
    environment:
      MYSQL_HOST: "db2:${MYSQL_PORT}"
      MYSQL_DB: "makeradmin-membership"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASS: "${MYSQL_PASS}"
      APIGATEWAY: "api-gateway"
      BEARER: "${API_BEARER}"
      HOST_FRONTEND:
      HOST_BACKEND:
      APP_DEBUG: "true"
    depends_on:
      - api-gateway
      - servicebase_python
    networks:
      - makeradmin

  webshop:
    image: makeradmin/webshop:1.0
    volumes:
      - "./webshop/src/ts:/var/www/service/ts"
      - "./webshop/src/scss:/var/www/service/scss"
      - "./webshop/src/templates:/var/www/service/templates"
    build: webshop
    ports:
      - "8011:80"
    environment:
      MYSQL_HOST: "db2:${MYSQL_PORT}"
      MYSQL_DB: "makeradmin-webshop"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASS: "${MYSQL_PASS}"
      APIGATEWAY: "api-gateway"
      BEARER: "${API_BEARER}"
      HOST_FRONTEND:
      HOST_BACKEND:
      APP_DEBUG: "true"
      STRIPE_PRIVATE_KEY:
      STRIPE_PUBLIC_KEY:
      STRIPE_SIGNING_SECRET:
    depends_on:
      - api-gateway
      - servicebase_python
    networks:
      - makeradmin

  rfid:
    image: makeradmin/rfid:1.0
    build: rfid
    environment:
      MYSQL_HOST: "db2:${MYSQL_PORT}"
      MYSQL_DB: "makeradmin-rfid"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASS: "${MYSQL_PASS}"
      APIGATEWAY: "api-gateway"
      BEARER: "${API_BEARER}"
      HOST_FRONTEND:
      HOST_BACKEND:
      APP_DEBUG: "true"
    depends_on:
      - api-gateway
      - servicebase_python
    networks:
      - makeradmin

  economy:
    image: makeradmin/economy:1.0
    build:
      context: ./economy
      dockerfile: ${PWD}/library/DockerfileService
    volumes:
      - ./logs/economy:/var/www/html/storage/logs
      - ./data/economy-vouchers:/var/www/html/vouchers
      - ./economy/lumen/routes:/var/www/html/routes
      - ./economy/lumen/app:/var/www/html/app
      - ./library/src/Makeradmin:/var/www/html/library
    environment:
      MYSQL_HOST: "db2:${MYSQL_PORT}"
      MYSQL_DB: "makeradmin-economy"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASS: "${MYSQL_PASS}"
      APIGATEWAY: "api-gateway"
      BEARER: "${API_BEARER}"
    depends_on:
      - api-gateway
    networks:
      - makeradmin

  membership:
    image: makeradmin/membership:1.0
    build:
      context: ./membership
      dockerfile: ${PWD}/library/DockerfileService
    volumes:
      - ./logs/membership:/var/www/html/storage/logs
      - ./membership/lumen/routes:/var/www/html/routes
      - ./membership/lumen/app:/var/www/html/app
      - ./library/src/Makeradmin:/var/www/html/library
    environment:
      MYSQL_HOST: "db2:${MYSQL_PORT}"
      MYSQL_DB: "makeradmin-membership"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASS: "${MYSQL_PASS}"
      APIGATEWAY: "api-gateway"
      BEARER: "${API_BEARER}"
    depends_on:
      - api-gateway
    networks:
      - makeradmin

  messages:
    image: makeradmin/messages:1.0
    build:
      context: ./messages
      dockerfile: ${PWD}/library/DockerfileService
    volumes:
      - ./logs/messages:/var/www/html/storage/logs
      - ./messages/lumen/routes:/var/www/html/routes
      - ./messages/lumen/app:/var/www/html/app
      - ./library/src/Makeradmin:/var/www/html/library
    environment:
      MYSQL_HOST: "db2:${MYSQL_PORT}"
      MYSQL_DB: "makeradmin-messages"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASS: "${MYSQL_PASS}"
      APIGATEWAY: "api-gateway"
      BEARER: "${API_BEARER}"
    depends_on:
      - api-gateway
    networks:
      - makeradmin

  email-dispatcher:
    image: makeradmin/messages-dispatcher-email:1.0
    build:
      context: ./emaildispatcher
      dockerfile: ${PWD}/library/DockerfileService
    volumes:
      - ./emaildispatcher/lumen/routes:/var/www/html/routes
      - ./emaildispatcher/lumen/app:/var/www/html/app
      - ./library/src/Makeradmin:/var/www/html/library
    environment:
      MYSQL_HOST: "db2:${MYSQL_PORT}"
      MYSQL_DB: "makeradmin-messages"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASS: "${MYSQL_PASS}"
      APIGATEWAY: "api-gateway"
      BEARER: "${API_BEARER}"
      MAILGUN_DOMAIN: "${MAILGUN_DOMAIN}"
      MAILGUN_KEY: "${MAILGUN_KEY}"
      MAILGUN_FROM: "${MAILGUN_FROM}"
    depends_on:
      - api-gateway
      - messages
    networks:
      - makeradmin

  multiaccesssync:
    image: makeradmin/multiaccesssync:1.0
    build:
      context: ./multiaccesssync
      dockerfile: ${PWD}/library/DockerfileService
    volumes:
      - ./data/multiaccess-uploads:/var/www/html/storage/uploads
      - ./multiaccesssync/lumen/routes:/var/www/html/routes
      - ./multiaccesssync/lumen/app:/var/www/html/app
      - ./library/src/Makeradmin:/var/www/html/library
    environment:
      APIGATEWAY: api-gateway
      BEARER: "${API_BEARER}"
    depends_on:
      - api-gateway
    networks:
      - makeradmin
      
  frontend:
    image: makeradmin/frontend:1.0
    build: ./frontend
    environment:
      HOST_BACKEND:
    ports:
      - "8009:80"
    networks:
      - makeradmin

networks:
  makeradmin:
volumes:
  dbdata:
